services:
  - type: web
    name: ahead-of-everyone-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_ID
        value: "6038057345"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
